# Appendix J: Tables for bias correction factors and scaling factors

For additional context see Appendix J of [The Virus of Variation](https://www.brokenquality.com/book). Questions? Email James.Lehner@gmail.com or QualityIsBroken@gmail.com.

In [2]:
# Import libraries
import pandas as pd

%matplotlib inline

## Get the data

The datasets are referenced in this appendix:

`table_J1_average_and_median_range_bias_correction_factors.csv`

`table_J2_average_range_scaling_factors.csv`

`table_J3_median_range_scaling_factors.csv`

The datasets can be found at https://github.com/jimlehner/virus-of-variation-book/tree/main/data.

In [3]:
# Get data function
def get_data(dataset_url) -> pd.DataFrame:
    return pd.read_csv(dataset_url)

In [4]:
# Bias correction factors url
bias_url = r'https://raw.githubusercontent.com/jimlehner/virus-of-variation-book/refs/heads/main/data/table_J1_average_and_median_range_bias_correction_factors.csv'

# Scaling factors using average range url
average_scaling_url = r'https://raw.githubusercontent.com/jimlehner/virus-of-variation-book/refs/heads/main/data/table_J2_average_range_scaling_factors.csv'

# Scaling factors using median range url
median_scaling_url = r'https://raw.githubusercontent.com/jimlehner/virus-of-variation-book/refs/heads/main/data/table_J3_median_range_scaling_factors.csv'

# Get data
bias_df = get_data(bias_url)

average_scaling_df = get_data(average_scaling_url)

median_scaling_df = get_data(median_scaling_url)

## Table J.1. Bias correction factors

In [5]:
bias_df

       n     d2      d3     d4  Unnamed: 4    n.1   d2.1    d3.1   d4.1
0    2.0  1.128  0.8525  0.954         NaN   21.0  3.778  0.7242  3.730
1    3.0  1.693  0.8884  1.588         NaN   22.0  3.819  0.7199  3.771
2    4.0  2.059  0.8798  1.978         NaN   23.0  3.858  0.7159  3.811
3    5.0  2.326  0.8641  2.257         NaN   24.0  3.895  0.1210  3.847
4    NaN    NaN     NaN    NaN         NaN    NaN    NaN     NaN    NaN
5    6.0  2.534  0.8480  2.471         NaN   25.0  3.931  0.7084  3.883
6    7.0  2.704  0.8332  2.645         NaN   30.0  4.086  0.6927  4.037
7    8.0  2.847  0.8198  2.791         NaN   35.0  4.213  0.6799  4.166
8    9.0  2.970  0.8078  2.915         NaN   40.0  4.322  0.6692  4.274
9   10.0  3.078  0.7971  3.024         NaN   45.0  4.415  0.6601  4.372
10   NaN    NaN     NaN    NaN         NaN    NaN    NaN     NaN    NaN
11  11.0  3.173  0.7873  3.121         NaN   50.0  4.498  0.6521  4.450
12  12.0  3.258  0.7785  3.207         NaN   55.0  4.572  0.6452  4.521
13  13.0  3.336  0.7704  3.285         NaN   60.0  4.639  0.6389  4.591
14  14.0  3.407  0.7630  3.356         NaN   65.0  4.699  0.6333  4.649
15  15.0  3.472  0.7562  3.422         NaN   70.0  4.755  0.6283  4.707
16   NaN    NaN     NaN    NaN         NaN    NaN    NaN     NaN    NaN
17  16.0  3.532  0.7499  3.482         NaN   75.0  4.806  0.6236  4.757
18  17.0  3.588  0.7441  3.538         NaN   80.0  4.854  0.6194  4.806
19  18.0  3.640  0.7386  3.591         NaN   85.0  4.898  0.6154  4.849
20  19.0  3.689  0.7335  3.640         NaN   90.0  4.939  0.6118  4.892
21  20.0  3.735  0.7287  3.686         NaN  100.0  5.015  0.6052  4.968

## Table J.2. Scaling factors using average range

In [6]:
average_scaling_df

       n     A2     D3     D4     E2
0    2.0  1.881     --  3.268  2.660
1    3.0  1.023     --  2.574  1.772
2    4.0  0.729     --  2.282  1.457
3    5.0  0.577     --  2.114  1.290
4    NaN    NaN    NaN    NaN    NaN
5    6.0  0.483     --  2.004  1.184
6    7.0  0.419  0.076  1.924  1.109
7    8.0  0.373  0.136  1.864  1.054
8    9.0  0.337  0.184  1.816  1.010
9   10.0  0.308  0.223  1.777  0.975
10   NaN    NaN    NaN    NaN    NaN
11  11.0  0.285  0.256  1.744  0.945
12  12.0  0.266  0.283  1.717  0.921
13  13.0  0.249  0.307  1.693  0.899
14  14.0  0.235  0.328  1.672  0.881
15  15.0  0.223  0.347  1.653  0.864

## Table J.3. Scaling factors using median range

In [7]:
median_scaling_df

       n     A4     D5     D6     E5
0    2.0  2.224     --  3.865  3.145
1    3.0  1.091     --  2.745  1.889
2    4.0  0.758     --  2.375  1.517
3    5.0  0.594     --  2.179  1.329
4    NaN    NaN    NaN    NaN    NaN
5    6.0  0.495     --  2.055  1.214
6    7.0  0.429  0.078  1.967  1.134
7    8.0  0.380  0.139  1.901  1.075
8    9.0  0.343  0.187  1.850  1.029
9   10.0  0.314  0.227  1.809  0.992
10   NaN    NaN    NaN    NaN    NaN
11  11.0  0.290   0.26  1.773  0.961
12  12.0  0.270  0.288  1.774  0.935
13  13.0  0.253  0.312  1.719  0.913
14  14.0  0.239  0.333  1.697  0.894
15  15.0  0.226  0.352  1.678  0.877